version: "27.2.0"

services:
  app:
    build: .

  db:
    image: postgres:16.3
    environment:
      -POSTGRES_DB=postgres
      -POSTGRES_USER=postgres
      -POSTGRES_PASSWORD=postgres
    
    ports:
      -5432:5432
    volumes:
      -./data/db:/var/lib/postgressql/data

