# Generated by Django 5.2 on 2025-05-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_countries_genre_language_subscriptionitems_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribers',
            unique_together={('user', 'subscribe_item')},
        ),
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=1200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='updated_at',
        ),
    ]
