# Generated by Django 5.2 on 2025-05-15 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chatadmin_admin_alter_chatadmin_user_chatadminanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatadmin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
