# Generated by Django 5.2 on 2025-05-16 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_chat_admin_message_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminanswer',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.chat'),
            preserve_default=False,
        ),
    ]
