# Generated by Django 5.2 on 2025-05-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_adminanswer_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminanswer',
            name='chat',
        ),
    ]
