# Generated by Django 5.2 on 2025-05-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default=1, max_length=30, verbose_name='device_id'),
            preserve_default=False,
        ),
    ]
