# Generated by Django 5.2 on 2025-05-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
