# Generated by Django 5.2 on 2025-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_premier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveBigIntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name='seriespart',
            name='season',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=5),
        ),
    ]
