# Generated by Django 5.2 on 2025-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_movie_like_movie_is_premier_movie_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriespart',
            name='season',
            field=models.CharField(choices=[('FIRST SEASON', 'first season'), ('SECOND SEASON', 'second season'), ('THIRD SEASON', 'third season'), ('FOURTH SEASON', 'fourth season'), ('FIFTY SEASON', 'fifty season')], db_default='FIRST SEASON', max_length=50),
        ),
    ]
