# Generated by Django 5.2 on 2025-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_favouritemovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.PositiveBigIntegerField(db_default=0),
        ),
    ]
