# Generated by Django 5.2 on 2025-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_movie_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED')], db_default='PENDING', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
