# Generated by Django 5.2 on 2025-05-19 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_translatemovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatemovies',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='translatemovies',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
