# Generated by Django 5.2 on 2025-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_translatemovies_telegram_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatemovies',
            name='user',
        ),
        migrations.AddField(
            model_name='translatemovies',
            name='telegram_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
