# Generated by Django 5.2 on 2025-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_translatemovies_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='trailer_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
