# Generated by Django 5.2 on 2025-05-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_news_trailer_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritemovies',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='SeriesPart',
        ),
    ]
