# Generated by Django 5.2 on 2025-05-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_season_episode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritemovies',
            unique_together={('movie',)},
        ),
    ]
