# Generated by Django 5.2 on 2025-05-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_paymentsubscription_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersubscription',
            name='payment_method',
            field=models.CharField(choices=[('PAYME', 'payme'), ('BALANCE', 'Balance')], db_default='BALANCE', max_length=25),
        ),
    ]
