# Generated by Django 5.2 on 2025-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_ordersubscription_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersubscription',
            name='payment_method',
        ),
    ]
