# Generated by Django 5.2 on 2025-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_ordersubscription_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BALANCE', 'balance'), ('PAYME', 'payme')], db_default='PAYME', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveBigIntegerField(db_default=0, verbose_name='user balance'),
        ),
    ]
