# Generated by Django 5.2 on 2025-05-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_ordersubscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('FAILED', 'failed'), ('COMPLETED', 'completed')], db_default='PENDING', max_length=25)),
                ('payment_method', models.CharField(choices=[('BALANCE', 'Balance'), ('PAYME', 'payme')], db_default='BALANCE', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.ordersubscriptionitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
