# Generated by Django 5.2 on 2025-05-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_paymentsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslateMovies',
        ),
    ]
