# Generated by Django 5.2 on 2025-05-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_delete_translatemovies'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie_fund', models.PositiveBigIntegerField(db_default=0)),
                ('collected_money', models.PositiveBigIntegerField(db_default=0)),
                ('is_finish', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
