# Generated by Django 5.2 on 2025-05-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_paymenttranslatemovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttranslatemovie',
            name='translate_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.translatemovies'),
        ),
    ]
