# Generated by Django 5.2 on 2025-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_paymenttranslatemovie_translate_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatemovies',
            name='collected_money',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
