name: Movie API CI

on: 
  push: 
    branches: [master]


jobs:
  test:
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_DB: movies
          POSTGRES_USER: mmovieapiadmin
          POSTGRES_PASSWORD: movie101101
        ports:
          -5432: 5432

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings


    steps:
      -uses: action/checkout@v2
      -uses: actions/setup-python@v2
      with:
        python-version: 3.12.4

      -name: install Requirments
      run: pip install -r requirements.txt
      -name: Run Tests
      run: pytest
  
  deploy:
    runs-on: ubuntu-latest

    needs: test
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: linuxserver.io
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami