name: Movie API CI

on: 
  push:

jobs:
  test:
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_DB: movies
          POSTGRES_USER: mmovieapiadmin
          POSTGRES_PASSWORD: movie101101
        ports:
          - 5432:5432  

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: pip install -r requirements.txt 
        
      - name: Setuptools
        run: pip install setuptools

      - name: Run Tests
        run: pytest
